### ISSUE TITLE
Negative Pos

### ISSUE THREAD

**Issue by saltas888** [milosmns/circular-slider-android#10]
Hello, I can't understand why Im getting negative values of pos.
Actually I see that the pos, moves on the range  -0,5...0.5.

**Comment by milosmns** [comment]
That value depends on your starting angle. Maybe take a look at #9, I commented there how to convert the values. I am planning on refactoring the behavior, but currently I'm swamped with other stuff. You're welcome to do it if you want to, just send a pull request and I'll take a look - but you'll probably be able to use what's written in #9.

**Comment by saltas888** [comment]
Thank's a lot Milos.
I hadn't read this issue detailed. Now it's clear.

Unfortunately, in the meantime I'm rushing with a big enough task, and I don't have any free time to change this behavior.

**Comment by milosmns** [comment]
Okay then, great if the other issue helped. You can try other conversions too - math is fun! :)
