### ISSUE TITLE
How to make slider in arc shape?

### ISSUE THREAD

**Issue by punithbm** [milosmns/circular-slider-android#11]
How to set angle of circle to make it arc 
![white dial](https://cloud.githubusercontent.com/assets/13044958/22459384/61b52eec-e7c6-11e6-8cb6-cd1abdb8f497.png)

Can you help us?

**Comment by milosmns** [comment]
Currently not possible with this View. You can:

1. Fork and add that functionality. Create a pull request with your changes and I can check it out.
2. You check other libraries such as
 - https://github.com/carlosrobles/ArcSeekBar
 - https://github.com/RaghavSood/AndroidCircularSeekBar
 - https://github.com/neild001/SeekArc

Let us know what you decided.

**Comment by punithbm** [comment]
Ok thank you

**Comment by milosmns** [comment]
No problem :) Hope that helped.
