### ISSUE TITLE
Border color and slider range color ?

### ISSUE THREAD

**Issue by indsoftdevelope** [milosmns/circular-slider-android#12]
Currently we can set only one color for border i want to use 2 different color how can i set for slider range and for border color ?

**Comment by milosmns** [comment]
This library only allows to go around, no arc drawing. 
Some other libraries that left allow you to do that:

https://github.com/devadvance/circularseekbar
https://github.com/neild001/SeekArc
https://github.com/JesusM/HoloCircleSeekBar
https://github.com/tankery/CircularSeekBar

You are also welcome to fork the repo and introduce the functionality yourself.
