### ISSUE TITLE
Can I make slider to be like seekbar?

### ISSUE THREAD

**Issue by vfongmala** [milosmns/circular-slider-android#16]
I would like to know that can I make circular slider like [this](https://drive.google.com/open?id=0B7RrLB2Vy0XzNVZkTkRpRVV6YkU) or not?

**Comment by milosmns** [comment]
See https://github.com/milosmns/circular-slider-android/issues/12
and https://github.com/milosmns/circular-slider-android/issues/5

Not meant to do that, there are alternatives available for what you need.
