### ISSUE TITLE
Consider a less restrictive License?

### ISSUE THREAD

**Issue by kevinchau** [milosmns/circular-slider-android#18]
Hi Milos,

This is a great project!

I would like to ask if you would consider changing the license from GPL to something less restrictive? I would really like to use your project in my app, but I'm unable to open source it.

Thanks!

**Comment by milosmns** [comment]
Oh, this was done a long time ago, don't worry. I picked one at random
really :) But I'm unable to change it right now, and don't want to keep you
waiting. So...

You are exempt from license rule, consider this a written confirmation.
Your non-open source usages are allowed.

**Comment by kevinchau** [comment]
Thanks Milos!
