### ISSUE TITLE
The slider is sometimes missing an angle

### ISSUE THREAD

**Issue by georgegijo** [milosmns/circular-slider-android#19]
Hi,

I am using the circular slider to make an element active when the slider angle matches with the angle of the element. Most of the time it works. But sometimes I have seen the slider misses the angle when the slider is moved fast.

**Comment by milosmns** [comment]
Hey,

Does it skip an angle even when super big? Try making it so big
(fullscreen) and let me know what happens. I'm thinking about the rounded
floating point issues, or maybe it has to do with main thread handling only
60fps (which means that your inputs might be capped to 1 every 16.67ms).
Let's try it out though :)

**Comment by georgegijo** [comment]
What I observed was as the speed of rotation increases it skips some angles. For my purpose now I am managed with a range so that the if the returned angle falls between a specified range, it activates the corresponding element. Thanks for replying.

**Comment by milosmns** [comment]
Okay, good to know.
