### ISSUE TITLE
How do I retrieve the angle?

### ISSUE THREAD

**Issue by Mikkelet** [milosmns/circular-slider-android#21]
Hey,

I've implemented the slider and it works so far, but I cannot see how I can retrieve the angle of the slider. I can see a lot of setters, such as setAngle, but no getters.

thanks

**Comment by milosmns** [comment]
Hey,

So you can attach a listener with `setOnSliderMovedListener` to get mathematical movement data. It involves a bit of maths. If you want a done solution for making the events user-friendly (say 0..100), I gave a hint here -- https://github.com/milosmns/circular-slider-android/issues/9
