### ISSUE TITLE
Feature Request: Add progress arc behind slider controll

### ISSUE THREAD

**Issue by ed-george** [milosmns/circular-slider-android#5]
If possible it would be great to see a solid color arc going from the top of the circle to the thumb control position to indicate the progress of the slider.

**Comment by milosmns** [comment]
I'm a bit swamped right now, but I welcome you to fork and do it yourself if you have some spare time. :) Leaving it open for now.

**Comment by milosmns** [comment]
There are other libraries that allow seeking. Since this is a slider, I'd like to recommend these ones as alternatives:

- https://github.com/carlosrobles/ArcSeekBar
- https://github.com/RaghavSood/AndroidCircularSeekBar
- https://github.com/neild001/SeekArc
