### ISSUE TITLE
Change slider value?

### ISSUE THREAD

**Issue by davin12x** [milosmns/circular-slider-android#6]
Right now it is  giving vale between 0 and 1 . is it possible to change it ?

**Comment by milosmns** [comment]
What would you change it to? Currently, it's the basic percentage. To get other values (let's say you need a range from `minRangeValue` to `maxRangeValue`) you could do something like

``` kotlin
/**
 * Converts the given percent value from [0, 1] range to a whole, integer from 
 * [minRangeValue, maxRangeValue] range.
 *
 * @param percentValue The percentage
 * @param minRangeValue Minimum allowed result integer
 * @param maxRangeValue Maximum allowed result integer
 */
fun convertPercentToRange(percentValue: Float, minRangeValue: Int, maxRangeValue: Int): Int {
    return minRangeValue + Math.round(percentValue * (maxRangeValue - minRangeValue))
}
```

This is Kotlin, but it's basically the same in Java, I just had this typed already. You can see the usage here:

https://gist.github.com/milosmns/32ade21cafded4bbd8bafe089ed79fd1

**Comment by milosmns** [comment]
With comments added to #9, this is now closed.
